#!/usr/bin/env bash

# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build app with one workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:  
  build:
    runs-on: ubuntu-latest
    container: node:16.14.2-alpine3.15

    steps:
    - uses: actions/checkout@v3

    - run: npm ci
    - run: npm run build --if-present

    - name: Build application
      run: yarn build

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USER }}/simplewhale:latest

    #- name: Build docker container
    #  run: /usr/bin/docker build -t dockerapiapp .

    #- name: Run docker container
    #  run: |
    #    /usr/bin/docker run -d -p 9999:9999 --name docker-api dockerapiapp
    #    /usr/bin/docker container ls

    - run: curl http://localhost:9999/api/foo/12


        
         
