#!/usr/bin/env bash

# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build app with one workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:  
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [16.x] 
          
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test   
    
    - name: Build application
      run: yarn build

    - name: Create artifact
    - uses: actions/upload-artifact@v3
      with:
        name: app-artifact
        path: src
  
  deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [16.x] 
    needs: [build]

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v1
      with:
        name: webapp-artifact
        path: src
        
    - name: Deploy to docker
      uses: tvrcgo/deploy-to-docker@v0.3.1
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: jazsodocker/first_test
        
        
    - name: actions-curl
      uses: enflo/curl-action@v1.2
      with:
        curl: http://localhost:9999/api/foo/12
  
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven and run automation testing
      run: mvn -B package --file auto_java/pom.xml -Dtest=TestFoo*
      
