# This workflow build and execute the api automation testing in the same job

name: Build app with one workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:  
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js environment
      uses: actions/setup-node@v3.1.0

    - run: npm ci

    - name: Build application
      run: yarn build

    - name: Build docker container
      run: docker build -t dockerapiapp .

    - name: Run docker container
      run: |
        docker run -d -p 9999:9999 --name docker-api dockerapiapp
        docker container ls

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build automation module
      run: mvn clean --file auto_java/pom.xml

    - name: Build automation module
      run: mvn -q test --file auto_java/pom.xml -Dtest=TestFooGet*

    - name: Build automation module
      run: mvn -q test --file auto_java/pom.xml -Dtest=TestFooPost*

    - name: Stop docker container
      run: |
        docker container ls
        docker stop docker-api
         
