#!/usr/bin/env bash

# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build app with one workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:  
  build:
    runs-on: ubuntu-latest
    #container: node:16.14.2-alpine3.15

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js environment
      uses: actions/setup-node@v3.1.0

    - run: npm ci

    - name: Build application
      run: yarn build

    - name: Build docker container
      run: docker build -t dockerapiapp .

    - name: Run docker container
      run: |
        docker run -d -p 9999:9999 --name docker-api dockerapiapp
        docker container ls



        
         
