# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build app

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:  
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [16.x]
    container: node:16.14.2-alpine3.15     # Docker Hub image that `container-job` executes in
    services:
      redis:
        image: redis
        # Map TCP port 9999 on Docker host to a random free port on the Redis container
        ports:
          - 9999/tcp
          
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test   
    
    - name: Build application
      run: yarn build
    
    - name: actions-curl
      # You may pin to the exact commit or the version.
      # uses: alesil/actions-curl@3bdc94d2e231b65cfafd795a820f99890b0603f6
      uses: alesil/actions-curl@v1.2
      with:
        # Curl parameters
        curl: http://127.0.0.1:9999/api/foo/12
  
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven and run automation testing
      run: mvn -B package --file auto_java/pom.xml -Dtest=TestFoo*
      
