# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build app

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Label of the container job
  container-job:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    #container: node:16.14.2-alpine3.15
    
    services:
      redis:
        image: redis
        # Map TCP port 9999 on Docker host to a random free port on the Redis container
        ports:
          - 9999/tcp
      tty: "true"
      stdin_open: "true"
    
    steps:
    - uses: actions/checkout@v3

    - name: Build and start app
      uses: comchangs/action-yarn@v0.1-beta
      with:
          build: yarn build
          start: yarn start
          wait-on: 'http://localhost:9999'
  
  build:
    needs: container-job
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven and run automation testing
      run: mvn -B package --file auto_java/pom.xml -Dtest=TestFoo*
