# This workflow build and execute the api automation testing in different jobs

name: Build app with using jobs (Disabled)

on:
  push:
    branches: [ disabled ]
  pull_request:
    branches: [ disabled ]

jobs:
  build:
    runs-on: ubuntu-latest
    #container: node:16.14.2-alpine3.15

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.1.0

      - run: npm ci

      - name: Build application
        run: yarn build

      - name: Build docker container
        run: docker build -t dockerapiapp .

      - name: Run docker container
        run: |
          docker run -d -p 9999:9999 --name docker-api dockerapiapp
          docker container ls

  test-get:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build automation module
        run: mvn clean --file auto_java/pom.xml

      - name: Build automation module
        run: mvn -q test --file auto_java/pom.xml -Dtest=TestFooGet*

  test-post:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build automation module
        run: mvn clean --file auto_java/pom.xml

      - name: Build automation module
        run: mvn -q test --file auto_java/pom.xml -Dtest=TestFooPost*

  stop-container:
    runs-on: ubuntu-latest
    needs: [ test-get, test-post ]

    steps:
      - name: Stop docker container
        run: |
          docker container ls
          docker stop docker-api
         
